# CI for Product Catalog Service (Java)

name: ad-ci

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: |
        cd src/product-catalog
        mvn clean install -DskipTests

    - name: Run Unit Tests
      run: |
        cd src/product-catalog
        mvn test

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run Checkstyle (or use SpotBugs/PMD)
      run: |
        cd src/product-catalog
        mvn checkstyle:check

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker Build and Push
      uses: docker/build-push-action@v6
      with:
        context: src/ad
        file: src/ad/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ad:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update tag in Kubernetes deployment manifest
      run: | 
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/ad:${{ github.run_id }}|" kubernetes/ad/deploy.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "nagarajudev9@gmail.com"
        git config --global user.name "Nagaraju Devulapalli"
        git add kubernetes/ad/deploy.yaml
        git commit -m "[CI]: Update ad image tag"
        git push origin HEAD:main -f
